apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: backend-app
type: Opaque
data:
  mongodb-username: dXNlcg==    # "mongoadmin" base64 encoded (echo -n user | base64)
  mongodb-password: cGFzc2Vy         # "password" base64 encoded (echo -n passer | base64))

