apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: ollama
  ports:
    - port: {{ .Values.ollama.servicePort }}
      targetPort: {{ .Values.ollama.servicePort }}
---
apiVersion: v1
kind: Service
metadata:
  name: webui-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: open-webui
  ports:
    - port: {{ .Values.webui.servicePort }}
      targetPort: {{ .Values.webui.servicePort }}
      nodePort: {{ .Values.webui.nodePort }}
